controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
      return $this->getData('index', ['articles']);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Get data from table.
     *
     * @param string $template
     *   Template name.
     * @param array $tables
     *   List of tables.
     *
     * @return string
     */
    public function getData($template, $tables)
    {
      $connection = \Yii::$app->db;

      $vars = [];
      foreach ($tables as $table) {
        $query = 'SELECT * FROM ' . $table . ';';
        $model = $connection->createCommand($query);
        $data = $model->queryAll();

        $vars[$table] = $data;
      }

      return $this->render($template, $vars);
    }

    /**
     * Displays articles page.
     *
     * @return string
     */
    public function actionArticles()
    {
      return $this->getData('articles', ['articles', 'links']);
    }

    /**
     * Displays links page.
     *
     * @return string
     */
    public function actionLinks()
    {
      return $this->getData('links', ['links', 'users']);
    }

    /**
     * Save article.
     *
     * @return string
     */
    public function actionSave_article()
    {
      $status = 'Error';
      if (isset($_GET['data']) && isset($_GET['data_text'])){
        $article_id = $_GET['data'];
        $text = $_GET['data_text'];

        // UPDATE article
        Yii::$app->db->createCommand()->update('articles', ['text' => $text], 'id = '.$article_id)->execute();
        $status = 'Success';
      }

      return $status;
    }

    /**
     * Get pay.
     *
     * @return string
     */
    public function actionGet_pay()
    {
      $status = 'Error';
      if (isset($_GET['data'])){
        $user_id = $_GET['data'];

        $connection = \Yii::$app->db;

        $query = 'SELECT summa FROM keepers WHERE user_id = '.$user_id.';';
        $model = $connection->createCommand($query);
        $summa = $model->queryOne();

        // UPDATE article
        Yii::$app->db->createCommand()->update('keepers', ['summa' => $summa['summa']-1], 'user_id = '.$user_id)->execute();
        $status = 'Success';
      }

      return $status;
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Click2pay',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Edit Articles', 'url' => ['/site/articles']],
            ['label' => 'Edit Links', 'url' => ['/site/links']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Click2pay <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>